config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  resources :users, only: [:show, :new, :create] do
    member do
      get :want_to_gos
      get :wents
    end
  end
  
  resources :restaurants, only: [:new]
  resources :visits, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  validates :name, presence: true, length: { maximum: 255 }
  validates :url, presence: true, length: { maximum: 255 }
  validates :image_url, presence: true, length: { maximum: 255 }
  validates :station, length: { maximum: 255, allow_blank: true }
  validates :category, presence: true, length: { maximum: 255 }
  validates :code, presence: true, length: { maximum: 255 }

  has_many :visits
  has_many :users, through: :visits
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  
  has_many :visits
  has_many :restaurants, through: :visits
  has_many :want_to_gos
  has_many :want_to_go_restaurants, through: :want_to_gos, class_name: 'Restaurant', source: :restaurant
  has_many :wents
  has_many :went_restaurants, through: :wents, class_name: 'Restaurant', source: :restaurant
  
  def want_to_go(restaurant)
    self.want_to_gos.find_or_create_by(restaurant_id: restaurant.id)
  end
  
  def unwant_to_go(restaurant)
    want_to_go = self.want_to_gos.find_by(restaurant_id: restaurant.id)
    want_to_go.destroy if want_to_go
  end
  
  def want_to_go?(restaurant)
    self.want_to_go_restaurants.include?(restaurant)
  end
  
  def went(restaurant)
    self.wents.find_or_create_by(restaurant_id: restaurant.id)
  end
  
  def unwent(restaurant)
    went = self.wents.find_by(restaurant_id: restaurant.id)
    went.destroy if went
  end
  
  def went?(restaurant)
    self.went_restaurants.include?(restaurant)
  end
end

app/models/visit.rb
class Visit < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant
end

app/models/want_to_go.rb
class WantToGo < Visit
end

app/models/went.rb
class Went < Visit
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include SessionsHelper
  
  private
  
  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
  
  def read(result)
    code = result['id']
    name = result['name']
    url = result['url']
    result['url']
    station = result['access']['station']
    category = result['category']
    
    if result['image_url']['shop_image1'].blank?
      image_url = '/images/noimage.jpg'
    else
      image_url = result['image_url']['shop_image1']
    end
    
    return {
      code: code,
      name: name,
      url: url,
      image_url: image_url,
      station: station,
      category: category
    }
  end
  
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :require_user_logged_in

  require 'net/http'
  require 'uri'
  require 'json'

  def new
    @restaurants = []

    @keyword = params[:keyword]
    if @keyword
      api_params = URI.encode_www_form({
        keyid: ENV['GNAVI_API_KEY_ID'],
        hit_per_page: 30,
        freeword: @keyword
      })
      uri = URI.parse("https://api.gnavi.co.jp/RestSearchAPI/v3/?#{api_params}")
      json = Net::HTTP.get(uri)
      results = JSON.parse(json)

      @count =  results['total_hit_count'].to_i

      if @count >= 1
        results['rest'].each do |result|
          restaurant = Restaurant.find_or_initialize_by(read(result))
          @restaurants << restaurant
        end
      end
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      redirect_to @user
    else
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
  
  private
  
  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      session[:user_id] = @user.id
      return true
    else
      return false
    end
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:show, :want_to_gos, :wents]
  
  def show
    @user = User.find(params[:id])
    @restaurants = @user.restaurants.uniq
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user
    else
      render :new
    end
  end
  
  def want_to_gos
    @user = User.find(params[:id])
    @restaurants = @user.want_to_go_restaurants
  end
  
  def wents
    @user = User.find(params[:id])
    @restaurants = @user.went_restaurants
  end
  
  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
  require 'net/http'
  require 'uri'
  require 'json'

  def create
    @restaurant = Restaurant.find_or_initialize_by(code: params[:code])

    unless @restaurant.persisted?
      api_params = URI.encode_www_form({
        keyid: ENV['GNAVI_API_KEY_ID'],
        id: @restaurant.code
      })
      uri = URI.parse("https://api.gnavi.co.jp/RestSearchAPI/v3/?#{api_params}")
      json = Net::HTTP.get(uri)
      results = JSON.parse(json)

      @restaurant = Restaurant.new(read(results['rest'][0]))
      @restaurant.save
    end

    if params[:type] == 'WantToGo'
      current_user.want_to_go(@restaurant)
    elsif params[:type] == 'Went'
      current_user.went(@restaurant)
    end

    redirect_back(fallback_location: root_path)
  end

  def destroy
    @restaurant = Restaurant.find(params[:restaurant_id])

    if params[:type] == 'WantToGo'
      current_user.unwant_to_go(@restaurant)
    elsif params[:type] == 'Went'
      current_user.unwent(@restaurant)
    end

    redirect_back(fallback_location: root_path)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    !!current_user
  end
end

app/views/layouts/_footer.html.erb
<footer class="text-center text-muted">
  <div class=
  <% if current_page?(controller: 'toppages', action: 'index') || current_page?(controller: 'sessions', action: 'new')%>
    "fixed"
  <% else %>
    "static"
  <% end %>
  >
    <p>© 2019 Miho Otsuka All Rights Reserved.</p>
    <p>Supported by <a href="http://api.gnavi.co.jp/api/scope/" target="_blank">ぐるなびWebService</a></p>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<header>
  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Lusikka</a>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>
            <li><%= link_to 'Search', new_restaurant_path %></li>
            <li><%= link_to 'My list', user_path(current_user) %></li>
            <li><%= link_to 'Log out', logout_path, method: :delete %></li>
          <% else %>
            <li><%= link_to 'Log in', login_path %></li>
            <li><%= link_to 'Sign up', signup_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Lusikka</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Josefin+Sans" rel="stylesheet">
    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>
    <% unless current_page?(controller: 'toppages', action: 'index') %>
      <%= render 'layouts/navbar' %>
    <% end %>
    
    <%= yield :cover %>

    <div class="container">
      <%= yield %>
    </div>

    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/restaurants/_restaurants.html.erb
<% if current_page?(controller: 'restaurants', action: 'new') && @count == 0 %>
  <div class="no-results-found">No results found</div>
<% else %>

  <% if restaurants %>
    <div class="row">
      <% restaurants.each do |restaurant| %>
        <div class="restaurant">
          <div class="col-md-3 col-sm-4 col-xs-12">
            <div class="panel panel-default">
              <div class="panel-heading text-center">
                <a href="<%= restaurant.url %>" target="_blank"><img src="<%= restaurant.image_url %>" alt="" ></a>
              </div>
              
              <div class="panel-body">
                <a href="<%= restaurant.url %>" target="_blank">
                  <div>
                    <p><%= restaurant.name %></p>
                    <p><%= restaurant.station %></p>
                    <p><%= restaurant.category %></p>
                  </div>
                </a>
                
                <div class="buttons text-center">
                  <% if logged_in? %>
                    <%= render 'visits/want_to_go_button', restaurant: restaurant %>
                    <%= render 'visits/went_button', restaurant: restaurant %>
                  <% end %>
                </div>
              </div>
              
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/restaurants/new.html.erb
<div class="search">
  <div class="row">
    <div class="col-xs-offset-1 col-xs-10 text-center">
      <%= form_tag(new_restaurant_path, method: :get, class: 'form-inline') do %>
        <div class="form-group">
          <%= text_field_tag :keyword, @keyword, class: 'form-control input-lg', placeholder: "Search…" , size: 40 %>
        </div>
        <%# submit_tag 'Search', class: 'btn' %>
      <% end %>
    </div>
  </div>
</div>

<%= render 'restaurants', restaurants: @restaurants %>

app/views/toppages/index.html.erb
<% content_for :cover do %>
  <div class="cover">
    <div class="cover-inner">
      <h1>Lusikka</h1>
        <ul class="top-menu">
          <% if logged_in? %>
            <li class="top-menu-item"><%= link_to 'Search', new_restaurant_path %></li>
            <li class="top-menu-item"><%= link_to 'My list', user_path(current_user) %></li>
            <li class="top-menu-item"><%= link_to 'Log out', logout_path, method: :delete %></li>
          <% else %>
            <li class="top-menu-item"><%= link_to 'Log in', login_path %></li>
            <li class="top-menu-item"><%= link_to 'Sign up', signup_path %></li>
        </ul>
      <% end %>
    </div>
  </div>
<% end %>

app/views/users/new.html.erb
<div class="row">
  <div class="user">
    <div class="col-sm-offset-1 col-sm-10 col-md-offset-3 col-md-6">
      <div class="panel panel-default">
        <div class="panel-heading">Sign up</div>
        <div class="panel-body">
          <%= form_for(@user) do |f| %>
            <div class="form-group">
              <%= f.label :name, 'Name' %>
              <%= f.text_field :name, class: 'form-control' %>
            </div>
  
            <div class="form-group">
              <%= f.label :email, 'E-mail' %>
              <%= f.email_field :email, class: 'form-control' %>
            </div>
  
            <div class="form-group">
              <%= f.label :password, 'Password' %>
              <%= f.password_field :password, class: 'form-control' %>
            </div>
  
            <div class="form-group">
              <%= f.label :password_confirmation, 'Password(confirmation)' %>
              <%= f.password_field :password_confirmation, class: 'form-control' %>
            </div>
  
            <%= f.submit 'Sign up', class: 'btn btn-block' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="user-profile">
  <div class="status text-center">
    <ul>
      <li>
        <div class="status-label">WANT</div>
      </li>
      <li>
        <div class="status-label">HAVE</div>
      </li>
    </ul>
  </div>
</div>
<%= render 'restaurants/restaurants', restaurants: @restaurants %>

app/views/users/want_to_gos.html.erb
<div class="row">
  <ul class="user-menu">
    <li><%= link_to 'All', user_path(@user) %></li>
    <li class="current"><%= link_to 'Want to go', want_to_gos_user_path(@user) %></li>
    <li><%= link_to 'Went', wents_user_path(@user) %></li>
  </ul>
</div>

<%= render 'restaurants/restaurants', restaurants: @restaurants %>

app/views/users/wents.html.erb
<div class="row">
  <ul class="user-menu">
    <li><%= link_to 'All', user_path(@user) %></li>
    <li><%= link_to 'Want to go', want_to_gos_user_path(@user) %></li>
    <li class="current"><%= link_to 'Went', wents_user_path(@user) %></li>
  </ul>
</div>

<%= render 'restaurants/restaurants', restaurants: @restaurants %>

app/views/visits/_want_to_go_button.html.erb
<% if current_user.want_to_go?(restaurant) %>
  <%= form_tag(visit_path(restaurant.id), method: :delete) do %>
    <%= hidden_field_tag :restaurant_id, restaurant.id %>
    <%= hidden_field_tag :type, 'WantToGo' %>
    <%= submit_tag 'Want to go', class: 'btn btn-unwant_to_go' %>
  <% end %>
<% else %>
  <%= form_tag(visits_path) do %>
    <%= hidden_field_tag :code, restaurant.code %>
    <%= hidden_field_tag :type, 'WantToGo' %>
    <%= submit_tag 'Want to go', class: 'btn' %>
  <% end %>
<% end %>

app/views/visits/_went_button.html.erb
<% if current_user.went?(restaurant) %>
  <%= form_tag(visit_path(restaurant.id), method: :delete) do %>
    <%= hidden_field_tag :restaurant_id, restaurant.id %>
    <%= hidden_field_tag :type, 'Went' %>
    <%= submit_tag 'Went', class: 'btn btn-unwent' %>
  <% end %>
<% else %>
  <%= form_tag(visits_path) do %>
    <%= hidden_field_tag :code, restaurant.code %>
    <%= hidden_field_tag :type, 'Went' %>
    <%= submit_tag 'Went', class: 'btn' %>
  <% end %>
<% end %>